Repository BoltApp/bolt-magento1, pull requests merged in 2019-02, with the labels that each got.

#292 Zero shipping tax on virtual orders
  app/code/community/Bolt/Boltpay/Model/BoltOrder.php
Labels: bugfix

#293 Discount types accessor
  app/code/community/Bolt/Boltpay/Model/BoltOrder.php
Labels: refactoring

#290 Shipping applied event
  app/code/community/Bolt/Boltpay/Model/Observer.php
  app/code/community/Bolt/Boltpay/Model/Order.php
Labels: enhancement

#289 Granulate bolt order creation
  app/code/community/Bolt/Boltpay/Model/BoltOrder.php
Labels: refactoring

#302 Cast to Array if String Value forEach
  app/code/community/Bolt/Boltpay/controllers/ShippingController.php
Labels: bugfix

#303 Ensure customer is logged in when saving the order
  app/code/community/Bolt/Boltpay/Model/Order.php
  app/code/community/Bolt/Boltpay/controllers/ApiController.php
Labels: bugfix

#272 PHPUnit tests: Adminhtml/Order/CreateController
  app/code/community/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateController.php
  tests/unit/testsuite/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateControllerTest.php
Labels: enhancement

#265 Promisifies the checkout process across one-page, multi-page, and admin
  app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
  app/code/community/Bolt/Boltpay/Helper/Data.php
  app/code/community/Bolt/Boltpay/Helper/Url.php
  app/code/community/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateController.php
  app/code/community/Bolt/Boltpay/controllers/OrderController.php
  app/code/community/Bolt/Boltpay/controllers/OrderControllerTrait.php
  app/design/adminhtml/default/default/template/boltpay/form.phtml
  app/design/frontend/base/default/template/boltpay/payment.phtml
  app/design/frontend/base/default/template/boltpay/replace_firecheckout.phtml
  tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
  tests/unit/testsuite/Bolt/Boltpay/TestHelper.php
Labels: enhancement

#153 Cache javascript cart code for same session, same order details
  app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
  app/code/community/Bolt/Boltpay/Helper/Data.php
  app/code/community/Bolt/Boltpay/Model/BoltOrder.php
  app/code/community/Bolt/Boltpay/controllers/OrderController.php
  app/code/community/Bolt/Boltpay/controllers/OrderControllerTrait.php
  tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
  tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
  tests/unit/testsuite/Bolt/Boltpay/TestHelper.php
Labels: enhancement

#308 comprehensive clearing of headers
  app/code/community/Bolt/Boltpay/controllers/ShippingController.php
Labels: bugfix

#317 correctly adds rules to cache and addresses shipping dependency on coupons
  app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
  app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
  app/code/community/Bolt/Boltpay/controllers/ShippingController.php
Labels: bugfix
