Repository BoltApp/bolt-magento1, pull requests merged in 2019-01, with the labels that each got.

#274 Adds on email enter event to Magento 1
  app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
  app/code/community/Bolt/Boltpay/Helper/Data.php
  app/code/community/Bolt/Boltpay/etc/system.xml
  tests/unit/testsuite/Bolt/Boltpay/TestHelper.php
Labels: enhancement

#275 Add support for item properties
  app/code/community/Bolt/Boltpay/Model/BoltOrder.php
  tests/unit/testsuite/Bolt/Boltpay/Model/BoltOrderTest.php
Labels: enhancement

#273 Prototype solution for price mismatches
  app/code/community/Bolt/Boltpay/Model/Order.php
  app/code/community/Bolt/Boltpay/Model/OrderFixer.php
  app/code/community/Bolt/Boltpay/Model/Payment.php
  app/code/community/Bolt/Boltpay/controllers/OrderController.php
  app/code/community/Bolt/Boltpay/etc/config.xml
  app/code/community/Bolt/Boltpay/etc/system.xml
  tests/unit/testsuite/Bolt/Boltpay/CouponHelper.php
  tests/unit/testsuite/Bolt/Boltpay/Model/CouponTest.php
  tests/unit/testsuite/Bolt/Boltpay/Model/OrderFixerTest.php
  tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
  tests/unit/testsuite/Bolt/Boltpay/OrderHelper.php
  tests/unit/testsuite/Bolt/Boltpay/TestHelper.php
Labels: enhancement

#276 Do a refund from the Bolt dashboard properly
  app/code/community/Bolt/Boltpay/Model/Payment.php
Labels: bug

#277 changes to classic form of `for` loop instead of `foreach` for IE11
  app/design/frontend/base/default/template/boltpay/replace_firecheckout.phtml
Labels: bug

#237 Implement product page checkout
  app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
  app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
  app/code/community/Bolt/Boltpay/Helper/Data.php
  app/code/community/Bolt/Boltpay/Helper/Transaction.php
  app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
  app/code/community/Bolt/Boltpay/controllers/OrderController.php
  app/code/community/Bolt/Boltpay/etc/config.xml
  app/code/community/Bolt/Boltpay/etc/system.xml
  app/design/frontend/base/default/layout/boltpay.xml
  app/design/frontend/base/default/template/boltpay/catalog/product/button.phtml
  app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
  app/design/frontend/base/default/template/boltpay/connectjs.phtml
  app/design/frontend/base/default/template/boltpay/replace.phtml
  app/design/frontend/base/default/template/boltpay/track.phtml
  tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
  tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
  tests/unit/testsuite/Bolt/Boltpay/TestHelper.php
Labels: enhancement

#280 Prefill the default shipping address for logged in customer
  app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
Labels: bug

#282 Move update payment status after order save
  app/code/community/Bolt/Boltpay/Model/Payment.php
Labels: bug

#283 Keep alive shipping and tax request
  app/code/community/Bolt/Boltpay/controllers/ShippingController.php
Labels: bugfix
