Repository BoltApp/bolt-magento1, pull requests merged in 2020-02, with the labels that each got.

#569 Unit Test: Helper/ApiTraitTest
  app/code/community/Bolt/Boltpay/Helper/ApiTrait.php
  tests/unit/testsuite/Bolt/Boltpay/Helper/ApiTraitTest.php
Labels: test

#624 Updates existing Bolt_Boltpay_Model_Order test. PR 3 or 3
  tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
Labels: do not merge, test

#623 Updates existing Bolt_Boltpay_Model_Order test. PR 2 or 3
  tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
Labels: do not merge, test

#622 Updates existing Bolt_Boltpay_Model_Order test. PR 1 of 3
  app/code/community/Bolt/Boltpay/Model/Order.php
  tests/unit/testsuite/Bolt/Boltpay/MockingTrait.php
  tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
Labels: test

#630 Frontend quantity check for Product Page
  app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
  app/code/community/Bolt/Boltpay/Helper/Data.php
  app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
  app/design/frontend/base/default/template/boltpay/popup.phtml
  tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php
  tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
Labels: bug, enhancement

#632 Complete Unit Test: Bolt_Boltpay_Adminhtml_Sales_Order_CreateController
  app/code/community/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateController.php
  tests/unit/testsuite/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateControllerTest.php
Labels: bug, test

#633 Complete unit test: Bolt_Boltpay_ApiController
  tests/unit/testsuite/Bolt/Boltpay/controllers/ApiControllerTest.php
Labels: test

#634 Validate Bolt order creation origin
  app/code/community/Bolt/Boltpay/Controller/Traits/WebHookTrait.php
  app/code/community/Bolt/Boltpay/Model/Order.php
  app/code/community/Bolt/Boltpay/controllers/ApiController.php
  tests/unit/testsuite/Bolt/Boltpay/Controller/Traits/WebHookTraitTest.php
  tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
  tests/unit/testsuite/Bolt/Boltpay/OrderHelper.php
Labels: bug

#635 PPC Refactor: Remove use of quote cloning
  app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
  tests/unit/testsuite/Bolt/Boltpay/Model/Productpage/CartTest.php
Labels: refactor

#637 Check for out-of-stock before saleable
  app/code/community/Bolt/Boltpay/Model/Order.php
  tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
Labels: bug

#636 Complete unit test: Bolt_Boltpay_Model_BoltOrder
  app/code/community/Bolt/Boltpay/Model/BoltOrder.php
  tests/unit/testsuite/Bolt/Boltpay/Model/BoltOrderTest.php
  tests/unit/testsuite/Bolt/Boltpay/TestHelper.php
Labels: test

#645 Add pending status to the default reception statuses
  app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
  tests/unit/testsuite/Bolt/Boltpay/Model/Admin/ExtraConfigTest.php
Labels: bug

#644 PPC Refactor: Utilize Bolt_Boltpay_Model_BoltOrder and Bolt_Boltpay_Block_Checkout_Boltpay
  app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
  app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
  app/code/community/Bolt/Boltpay/Helper/Data.php
  app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
  app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
  tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php
  tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
  tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
  tests/unit/testsuite/Bolt/Boltpay/Helper/GeneralTraitTest.php
  tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
  tests/unit/testsuite/Bolt/Boltpay/Model/Productpage/CartTest.php
Labels: refactor

#651 Supply default value for optional parameter for Bolt_Boltpay_Model_BoltOrder::addShippingForAdmin
  app/code/community/Bolt/Boltpay/Model/BoltOrder.php
Labels: bug

#652 Add support for configurable products on PPC
  app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
  app/code/community/Bolt/Boltpay/Helper/Data.php
  app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
  app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
  tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php
  tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
  tests/unit/testsuite/Bolt/Boltpay/Model/Productpage/CartTest.php
Labels: enhancement
